services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: measures
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: MDGcontra2021
      PGTZ: Europe/Madrid # Hint for clients
      TZ: Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:


